{% set name = "Orange3-Text" %}
{% set version = "0.2.4" %}
{% set sha256 = "7b71547d65d592a54ccd551ffdae20065dcafabcc2a84014321b33c27b69872d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - biopython
    - scipy
    - nltk            >=3.0.5
    - scikit-learn
    - numpy
    - gensim          >=0.12.3
    - setuptools-git
    - orange3         >=3.3.9
    - beautifulsoup4
    - validate_email
    - tweepy
    - simhash
    - wikipedia
    - pyqt            4.11.*
    - typing

test:
  imports:
    - orangecontrib.text

about:
  home: https://github.com/biolab/orange3-text
  license: AGPLv3
  license_family: AGPL
  license_file: LICENSE
  summary: 'Orange3 addon for analysing textual data.'

  description: |
    Orange add-on for text mining. It provides access to publicly available
    data, like NY Times, Twitter and PubMed. Further, it provides tools for
    preprocessing, constructing vector spaces (like bag-of-words and topic
    modeling) and visualizations like word cloud end geo map. All features
    can be combined with powerful data mining techniques from the Orange
    data mining framework.

  doc_url: http://orange3-text.readthedocs.io
  dev_url: https://github.com/biolab/orange3-text

extra:
  recipe-maintainers:
    - nikicc
