# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fsSKpRl0rNsinBc1Zw14yQiYy25//QhbadZf1IWBlENanT4PJTqYT3+G/29xd8nUVkvVpKk+/HmhCWshpSgfH2WR6O/q78dFDPrXSdlU+k4RlXG1AzD+GWz94YSb80pv18cGa9QGVW+a9xddYnj43PM2h2gVaARwNq9vagsQQ2yVCG3pypitZLXpv6AFy80mJJUBl/76t0tNBzFMZpInF67zulPakwpWNL95BEtm9on+DRaHh1IMj1B7DrOiLPa6W9uDDunIUeC8OAaE7u791U+11C4SPMaDfKbWTV5pE9xXfqeZblUsYmETktaF+rhHizxz8ekIzv4hFf2i1IDwFy+nDnHcRqWquEHFKv2d+lcHJjvkyE3eD169WtsnsKVuW4TfC0uRgpg0tLLWu3vAQQN9fS5HGh5hIUzaukNZ3dWhXIssN4YUL5f39DT6vAFam2bTO/C5xl/PvOBRfcq3NhTNJolzIj+yVAqOJyYsKoiiEqHc3izRGZLZQdl7f2W2XgkYncAS1YAeUTFQlVAPUV/UW47bW3LJh2ENiZ4e1l1d4Jcrsh9Xz8BSUQzdPsbJDTcSaq1yJyhMS9a52MotPqUfJ/lTgpNthZXw/PCubxTl3MTM5IRSMByR/p6rYXtjiY0pLo00BmA6T9vF8YpmRQM+CXUY3q8ZaG1lFj1NBys="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
