travis:
  secure:
    BINSTAR_TOKEN: MhwFBQmvwXdphlV2cEwS9CfI6+lkLPFZjU4+H2XJ1NV19w0S92VqZhIMpDkWrz9CjSsezaHg4GdopudnBTpWswZLtj63M364Q5bqnVtLaY/fxE3pfqovs09fNqeQ4VpbmlVL7u64Zu4DCCcKk7UQHaGtI8RZp7sDBqe/jBoTHnkliLSorHNmuS3d0+YF2bdY9vtKcEFaVf6YT8MrNSLmcHgqNGGP1y+TnqAf2Dvc052o1OsV3WwqgTlfI22DEsCY1YvZJQ86fYG29I2jjhXv2K/BuNLUGb+8DHUYiQbETw0rOWknKTWqFJj+icfYTHVWhUX0rkts11DIdq/EKbXGRVbi6KSJHPRExVOJwkUN/ZQegZLeZtQ0EKDWZF8KvSpP8l6C3ui0QdCzoNu5Qcb8xwjgNZK/QCER9i8MHXEU1FmGRd0QaMaRvZckxyTxYQwO/XNMy3V2PPny5nJmZ95QWuseIlc4+wEslCkegkrJmk7n1WRjuMm/UdB93mf4i7xurHlGB2Q9BvW5qHs7TsQpIGFtY/RQz89bvmTHRz2lYlR/FGxo07wgI1aYRwW5UIbco0dI1jFf61RzMnNRJUa0AKWzDU0QZ0f8ZAMqxb9bLMleD2VPJfOUAVWM0pXbBktHZE429HGMTZLTBnQCuIqFVQEdrpA/tD8b4e4gvCZNFYU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
